### ISSUE TITLE
🐛  Modify the display format of the balances in the bot interface

### ISSUE THREAD

**Issue by cmnisal** [CeyLabs/BitcoinDeepaBot#8]
## Task

As a developer, I want to format the LKR and USD balances with commas so I can enhance readability for users.
also I want to update the text on the keyboard buttons to improve the user experience.

## Acceptance Criteria

- [ ] AC1: The LKR and USD balances should be displayed in comma-separated format.
- [ ] AC2: Test the changes to ensure that the format is consistently applied across all displayed balances.
- [ ] AC3: Gather suggestions or guidelines for the new text for keyboard buttons.
- [ ] AC4: Implement the changes based on the gathered suggestions.
- [ ] AC5: Test the new button text to ensure it enhances user interaction.

## Assets

- Mockup: 
![image](https://github.com/user-attachments/assets/874ad3ca-1d7f-4ba2-b8e6-266dfb97a955)

![image](https://github.com/user-attachments/assets/84d28ef6-d691-460a-9280-b534ed0fd05e)

**Comment by cmnisal** [comment]
#17 PR
